name: mt3-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow[and-cuda]
      - git+https://github.com/google-research/t5x#egg=t5x
      - git+https://github.com/magenta/mt3.git
      - jax[cuda12]
      - librosa
      - note-seq
      - seqio
      - t5
      - typeguard>=4.0.1
      - nest-asyncio
      - pyfluidsynth==1.3.0
      - gin-config
